### ISSUE TITLE
Upload to Hackage

### ISSUE THREAD

**Issue by pepeiborra** [haskell/lsp#348]
This is required to upload the next release of HLS to Hackage (https://github.com/haskell/haskell-language-server/pull/2052)

/cc @wz1000 @alanz @bubba

**Comment by jneira** [comment]
It would be great if the list of hackage maintainers could include some other hls ones.

**Comment by wz1000** [comment]
Candidates uploaded to:

https://hackage.haskell.org/package/lsp-types-1.3.0.0/candidate
https://hackage.haskell.org/package/lsp-test-0.14.0.1/candidate
https://hackage.haskell.org/package/lsp-1.2.0.1/candidate

I have added @pepeiborra and @jneira as hackage maintainers.

I'm waiting for CI to give the green light on https://github.com/haskell/lsp/commit/dec07c6182f9c42abdac1a043caff7bcff85f81e before publishing.

**Comment by wz1000** [comment]
Published!

**Comment by bkomuves** [comment]
Both the Hackage CI and the Matrix Builder (I'm not sure if these are separate entities or not?) fails to build lsp-types-1.3.0.0: 

* https://matrix.hackage.haskell.org/#/package/lsp-types/
* https://hackage.haskell.org/package/lsp-types-1.3.0.0/reports/

which in turn also means that there is no browsable documentation on Hackage.

Since it builds locally (with ghc 8.6.5 in my case), I would guess that the reason is maybe that some dependencies have a not-strict-enough version bound?

**Comment by alanz** [comment]
I think I used to use the [neil](https://hackage.haskell.org/package/neil) to publish locally built docs to hackage, there was a problem building them via hackage. I thing is is because the package uses an extension (overloaded record fields?) which was not supported in the version building docs, or something.

**Comment by jneira** [comment]
Opened an issue about #349
